In [4]:
import numpy as np
#creating arrays
arr1=np.array([1,2,3,4,5]) #1D array
arr2=np.array([[1,2,3],[4,5,6]]) #2D array

#Arry operations(vectorization)
print(arr1*2) #Multiply each element by 2
print(arr1+arr1) #Add arrays element-wise

#Reshaping
arr3=np.arange(12).reshape(3,4) #Create 3x4 array from 0-11
print(arr3)

#Matrix operations
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2)) #matrix multiplication

#Statistical operations
data=np.random.normal(0,1,1000)
print(f"Mean: {data.mean()},std: {data.std()}")

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean: 0.04651877202262311,std: 1.0233636234295236


In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5]) 
arr2=np.array([[1,2,3],[4,5,6]]) 
print(arr1*2) 
print(arr1+arr1)
arr3=np.arange(12).reshape(3,4) 
print(arr3)
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2)) 
data=np.random.normal(0,1,1000)
print(f"Mean: {data.mean()},std: {data.std()}")

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean: -0.024516639599143446,std: 1.0022057006156346


In [7]:
import pandas as pd
import numpy as np

# Creating dataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print(df)

# Reading from CSV (commented out)
# df = pd.read_csv('data.csv')

# Basic operations
print(df.head(2))  # First 2 rows
print(df.describe())  # Summary statistics
print(df['Age'].mean())  # Average age

# Data Selection
print(df[df['Age'] > 30])  # Filtering
print(df.loc[1:2, ['Name', 'Salary']])  # Selection by label

# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]
})
print(df_with_nan.fillna(value=0))  # Replace NaN with 0
print(df_with_nan.dropna())  # Drop rows with NaN

# Grouping and aggregation
df['Department'] = ['HR', 'Tech', 'Tech', 'HR']
# Fix: Explicitly select numeric columns for aggregation
print(df.groupby('Department')[['Age', 'Salary']].mean())  # Average by department

# Merging DataFrames (like SQL joins)
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve'],
    'Bonus': [2000, 1500, 3000]
})
print(pd.merge(df, df2, on='Name', how='left'))  # Left join

# Time series functionality
date_rng = pd.date_range(start='1/1/2023', end='1/10/2023', freq='D')
ts = pd.DataFrame(date_rng, columns=['date'])
ts['value'] = np.random.randint(0, 100, size=(len(date_rng)))
ts.set_index('date', inplace=True)
print(ts.resample('3D').mean())  # Resample to 3-day periods

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000
             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000
32.5
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
      Name  Salary
1      Bob   60000
2  Charlie   70000
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0
     A    B
0  1.0  5.0
3  4.0  8.0
             Age   Salary
Department               
HR          32.5  65000.0
Tech        32.5  65000.0
      Name  Age  Salary Department   Bonus
0    Alice   25   50000         HR  2000.0
1      Bob   30   60000       Tech  1500.0
2  Charlie   35   70000       Tech     NaN
3    David   40   80000      